'use strict';
const $=id=>document.getElementById(id);
const GD=window.GameData;
const {COLS,ROWS,TILE_SIZE,FIELD_W:W,FIELD_H:H,OFFSET_X,OFFSET_Y,HQ_COL,HQ_ROW,PLAYER_SPAWN,SPAWN_POINTS,ENEMY_TYPES,CAMPAIGN_LEVELS,buildLevelMap,key}=GD;
const c=$('c'),ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;
if((navigator.maxTouchPoints||0)>0||matchMedia('(pointer:coarse)').matches)document.body.classList.add('touch');
const DIRS=['up','down','left','right'];
const dv=d=>d==='up'?[0,-1]:d==='down'?[0,1]:d==='left'?[-1,0]:[1,0];
const hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const rand=(a,b)=>a+Math.random()*(b-a);
const px=c=>OFFSET_X+c*TILE_SIZE,py=r=>OFFSET_Y+r*TILE_SIZE;
const cellCenter=(c,r)=>({x:px(c)+TILE_SIZE/2,y:py(r)+TILE_SIZE/2});
const rectForCell=(c,r,pad=0)=>({x:px(c)+pad,y:py(r)+pad,w:TILE_SIZE-pad*2,h:TILE_SIZE-pad*2});
const centerCell=t=>({c:clamp(Math.floor((t.x+t.w/2-OFFSET_X)/TILE_SIZE),0,COLS-1),r:clamp(Math.floor((t.y+t.h/2-OFFSET_Y)/TILE_SIZE),0,ROWS-1)});
let raf=0,last=0,lastFrameWall=performance.now(),running=false,paused=false;
let score=0,lives=3,levelIndex=0,waveIndex=0,levelStartScore=0,retriesRemaining=2;
let spawnQueue=[],spawnTimer=0,spawnCursor=0,waveTransition=0,fireCd=0,rapidUntil=0,shieldUntil=0,hqInvulnUntil=0;
let player,enemies=[],bullets=[],obstacles=[],iceCells=new Set(),bushCells=new Set(),base,keys={},particles=[],pickups=[],kills=0,soundOn=true,audioCtx=null,primaryMode='restart';
let touch={active:false,id:null,x:0,y:0,max:42},refitTimer=0;
function audio(){if(!soundOn)return null;try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch{return null}}
function tone(freq=220,dur=.05,type='square',gain=.035,slide=0){const ac=audio();if(!ac)return;const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,ac.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(25,freq+slide),ac.currentTime+dur);g.gain.setValueAtTime(gain,ac.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+dur);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+dur)}
function sfx(name){if(name==='shot')tone(220,.045,'square',.025,80);else if(name==='boom'){tone(90,.13,'sawtooth',.045,-55);setTimeout(()=>tone(55,.09,'square',.025,-20),25)}else if(name==='hurt')tone(120,.12,'square',.045,-65);else if(name==='hq')tone(150,.16,'sawtooth',.055,-80);else if(name==='power'){tone(420,.08,'square',.035,260);setTimeout(()=>tone(650,.09,'square',.03,180),70)}else if(name==='win'){tone(520,.11,'square',.035,160);setTimeout(()=>tone(720,.13,'square',.035,180),120)}else if(name==='wave')tone(380,.06,'square',.025,110);else if(name==='lose')tone(170,.28,'sawtooth',.04,-110)}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1450)}
function brickSegmentRects(o){const hs=TILE_SIZE/2,arr=[];for(let bit=0;bit<4;bit++)if(o.segments&(1<<bit)){const dx=(bit%2)*hs,dy=(bit>1?1:0)*hs;arr.push({x:o.x+dx,y:o.y+dy,w:hs,h:hs,bit})}return arr}
function obstacleRects(o){if(o.type==='BRICK')return brickSegmentRects(o);if(o.type==='STEEL'||o.type==='WATER')return [{x:o.x,y:o.y,w:o.w,h:o.h,bit:-1}];return []}
function isSolidForTank(o){return o.type==='BRICK'||o.type==='STEEL'||o.type==='WATER'}
function collidesEnvironment(t){for(const o of obstacles)if(isSolidForTank(o))for(const r of obstacleRects(o))if(hit(t,r))return true;return false}
function collidesTank(t){if(base&&base.alive&&hit(t,base))return true;if(player&&player!==t&&player.alive&&hit(t,player))return true;for(const e of enemies)if(e!==t&&e.alive&&hit(t,e))return true;return false}
function moveEntity(t,dx,dy){let blocked=false;const steps=Math.max(1,Math.ceil(Math.max(Math.abs(dx),Math.abs(dy))/6)),sx=dx/steps,sy=dy/steps;for(let i=0;i<steps;i++){const ox=t.x,oy=t.y;t.x=clamp(t.x+sx,OFFSET_X+1,OFFSET_X+COLS*TILE_SIZE-t.w-1);t.y=clamp(t.y+sy,OFFSET_Y+1,OFFSET_Y+ROWS*TILE_SIZE-t.h-1);if(collidesEnvironment(t)||collidesTank(t)){t.x=ox;t.y=oy;blocked=true;break}}return blocked}
function onIce(t){const cc=centerCell(t);return iceCells.has(key(cc.c,cc.r))}
function tileBlocked(cc,rr){if(cc<0||cc>=COLS||rr<0||rr>=ROWS)return true;const q=rectForCell(cc,rr,4);return obstacles.some(o=>isSolidForTank(o)&&obstacleRects(o).some(s=>hit(q,s)))||(base&&base.alive&&hit(q,base))}
function createObstacle(data){const r=rectForCell(data.c,data.r,0);if(data.type==='BRICK'){let segments=15;if(data.damage===1)segments=15^(1<<((data.c+data.r)%4));return {...r,c:data.c,r:data.r,type:'BRICK',segments}}return {...r,c:data.c,r:data.r,type:data.type,segments:0}}
function addHQFortification(level){let cells=[[9,11],[10,11],[11,11],[9,12],[11,12]];if(level.id===41)cells=[[10,11],[9,12],[11,12]];for(const [cc,rr] of cells)obstacles.push(createObstacle({c:cc,r:rr,type:'BRICK'}));if(level.id===50){for(const cc of [7,8,9,10,11,12,13])if(cc!==10)obstacles.push(createObstacle({c:cc,r:10,type:'BRICK'}))}}
function buildRuntimeMap(level){const built=buildLevelMap(level),map=built.map;obstacles=[...map.obstacles.values()].map(createObstacle);iceCells=new Set(map.ice);bushCells=new Set(map.bush);addHQFortification(level);return built.features}
function makeBase(){const cent=cellCenter(HQ_COL,HQ_ROW),w=38,h=34;return {x:cent.x-w/2,y:cent.y-h/2,w,h,alive:1,hp:3,maxHp:3}}
function spawnPlayer(){const cent=cellCenter(PLAYER_SPAWN.c,PLAYER_SPAWN.r);player={x:cent.x-16,y:cent.y-18,w:32,h:36,dir:'up',speed:180,alive:1,vx:0,vy:0};if(collidesEnvironment(player)||hit(player,base)){for(const [cc,rr] of [[7,12],[6,12],[8,11],[7,10],[6,10]]){const p=cellCenter(cc,rr);player.x=p.x-16;player.y=p.y-18;if(!collidesEnvironment(player)&&!hit(player,base))break}}}
function resetCampaign(){score=0;lives=3;kills=0;rapidUntil=0;shieldUntil=0;levelIndex=0;retriesRemaining=2;levelStartScore=0;startLevel()}
function startLevel(){const level=CAMPAIGN_LEVELS[levelIndex];spawnQueue=[];spawnTimer=.15;spawnCursor=0;waveIndex=0;waveTransition=0;fireCd=0;enemies=[];bullets=[];particles=[];pickups=[];keys={};hqInvulnUntil=0;base=makeBase();const features=buildRuntimeMap(level);spawnPlayer();levelStartScore=score;beginWave(0);stats();last=performance.now();lastFrameWall=last;running=true;paused=false;$('over').classList.add('hidden');$('pauseModal').classList.add('hidden');cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);toast(`Уровень ${level.id}: ${level.name}${features.length?' · '+features.join(' + '):''}`);fitGameBurst()}
function beginWave(idx){waveIndex=idx;spawnQueue=[...CAMPAIGN_LEVELS[levelIndex].waves[idx]];spawnTimer=.15;waveTransition=0;stats();sfx('wave');toast(`Волна ${idx+1}/3`)}
function stats(){const level=CAMPAIGN_LEVELS[levelIndex];$('score').textContent=score;$('lives').textContent=lives;$('level').textContent=`${level.id}/50`;$('wave').textContent=`${waveIndex+1}/3`;$('enemies').textContent=enemies.length+spawnQueue.length;const full='❤'.repeat(Math.max(0,base?.hp||0)),empty='♡'.repeat(Math.max(0,(base?.maxHp||3)-(base?.hp||0)));$('hq').textContent=full+empty}
function getSpawnRect(sp){const p=cellCenter(sp.c,sp.r),w=32,h=36;return {x:p.x-w/2,y:p.y-h/2,w,h}}
function spawnEnemy(){if(!spawnQueue.length)return false;const level=CAMPAIGN_LEVELS[levelIndex],names=level.spawnPoints;for(let tries=0;tries<names.length;tries++){const name=names[(spawnCursor+tries)%names.length],sp=SPAWN_POINTS[name],rect=getSpawnRect(sp);if(collidesEnvironment(rect)||enemies.some(e=>e.alive&&hit(rect,e))||(player?.alive&&hit(rect,player)))continue;const type=spawnQueue.shift(),cfg=ENEMY_TYPES[type];enemies.push({...rect,dir:sp.dir||'down',speed:cfg.speed,turn:rand(.35,.9),fire:rand(...cfg.fireInterval),alive:1,type,hp:cfg.hp,maxHp:cfg.hp,color:cfg.color,score:cfg.score,bulletSpeed:cfg.bulletSpeed,vx:0,vy:0});spawnCursor=(spawnCursor+tries+1)%names.length;return true}return false}
function chooseEnemyDir(e){const cc=centerCell(e),dirs=DIRS.filter(d=>{const [dx,dy]=dv(d);return !tileBlocked(cc.c+dx,cc.r+dy)});if(!dirs.length)return e.dir;let best=dirs[0],bestScore=Infinity;for(const d of dirs){const [dx,dy]=dv(d),nc=cc.c+dx,nr=cc.r+dy;let s=Math.abs(HQ_COL-nc)+Math.abs(HQ_ROW-nr)+Math.random()*2.2;if(d==='down')s-=1.5;if(d===e.dir)s-=.6;if(s<bestScore){bestScore=s;best=d}}return best}
function shoot(t,owner){const [dx,dy]=dv(t.dir),s=7,rapid=owner==='p'&&performance.now()<rapidUntil,speed=owner==='p'?520:(t.bulletSpeed||315);bullets.push({x:t.x+t.w/2-s/2+dx*(t.w/2+5),y:t.y+t.h/2-s/2+dy*(t.h/2+5),w:s,h:s,dx,dy,speed,owner,power:rapid?2:1});if(owner==='p')sfx('shot')}
function explosion(x,y,col='#f6b44b',count=14){for(let i=0;i<count;i++)particles.push({x,y,vx:rand(-150,150),vy:rand(-150,150),life:rand(.2,.55),max:.55,size:rand(3,8),col})}
function maybeDrop(x,y){if(kills%4!==0)return;const types=['rapid','shield','life','repair'],kind=types[Math.floor(Math.random()*types.length)];pickups.push({x:x-12,y:y-12,w:24,h:24,kind,life:11})}
function applyPickup(p){if(p.kind==='rapid'){rapidUntil=performance.now()+9000;toast('⚡ Скорострельность: 9 сек.')}else if(p.kind==='shield'){shieldUntil=performance.now()+9000;toast('🛡 Щит: 9 сек.')}else if(p.kind==='repair'){if(base.hp<base.maxHp){base.hp++;toast(`🔧 Штаб: ${base.hp}/${base.maxHp}`)}else{score+=150;toast('🔧 Штаб цел — +150')}}else{lives=Math.min(5,lives+1);toast('❤ +1 жизнь')}sfx('power');p.dead=1;stats()}
function damagePlayer(){if(performance.now()<shieldUntil){sfx('power');toast('Щит поглотил попадание');return}lives--;explosion(player.x+16,player.y+18,'#74e0a1',18);sfx('hurt');if(lives<=0){player.alive=0;finish(false,'Танк уничтожен')}else{spawnPlayer();shieldUntil=performance.now()+1800;toast(`Осталось жизней: ${lives}`)}stats()}
function damageBase(){const now=performance.now();if(now<hqInvulnUntil||!base.alive)return;hqInvulnUntil=now+420;base.hp=Math.max(0,base.hp-1);explosion(base.x+base.w/2,base.y+base.h/2,base.hp>0?'#f2ca4b':'#ff6b5f',base.hp>0?15:34);sfx(base.hp>0?'hq':'lose');stats();if(base.hp<=0){base.alive=0;finish(false,'Штаб уничтожен')}else toast(`⚠ Штаб повреждён: ${base.hp}/${base.maxHp}`)}
function damageBrick(o,b){const segs=brickSegmentRects(o).filter(r=>hit(b,r));if(!segs.length)return false;const s=segs[0];o.segments&=~(1<<s.bit);explosion(b.x,b.y,'#b86a4e',5);return true}
function bulletHitsObstacle(b){for(const o of obstacles){if(o.type==='WATER')continue;if(o.type==='STEEL'&&hit(b,o)){b.dead=1;explosion(b.x,b.y,'#8d99aa',3);return true}if(o.type==='BRICK'&&damageBrick(o,b)){b.dead=1;return true}}return false}
function updatePlayer(dt){if(!player?.alive)return;let ix=0,iy=0;if(keys.up)iy=-1;else if(keys.down)iy=1;else if(keys.left)ix=-1;else if(keys.right)ix=1;const ice=onIce(player),targetX=ix*player.speed,targetY=iy*player.speed;if(ix||iy){if(Math.abs(ix)>Math.abs(iy))player.dir=ix>0?'right':'left';else player.dir=iy>0?'down':'up';const blend=ice?Math.min(1,dt*3.2):1;player.vx+=(targetX-player.vx)*blend;player.vy+=(targetY-player.vy)*blend}else if(ice){const decay=Math.exp(-dt*2);player.vx*=decay;player.vy*=decay;if(Math.abs(player.vx)<3)player.vx=0;if(Math.abs(player.vy)<3)player.vy=0}else{player.vx=0;player.vy=0}const blocked=moveEntity(player,player.vx*dt,player.vy*dt);if(blocked){player.vx*=.1;player.vy*=.1}fireCd-=dt;const rate=performance.now()<rapidUntil?.14:.30;if(keys.fire&&fireCd<=0){shoot(player,'p');fireCd=rate}}
function updateEnemies(dt){for(const e of enemies){const ice=onIce(e);e.turn-=dt;e.fire-=dt;if(e.turn<=0){e.dir=chooseEnemyDir(e);e.turn=rand(ice?.75:.32,ice?1.35:.9)}const [dx,dy]=dv(e.dir),targetX=dx*e.speed,targetY=dy*e.speed,blend=ice?Math.min(1,dt*2.4):1;e.vx+=(targetX-e.vx)*blend;e.vy+=(targetY-e.vy)*blend;const blocked=moveEntity(e,e.vx*dt,e.vy*dt);if(blocked){e.vx=0;e.vy=0;e.dir=chooseEnemyDir(e);e.turn=.12}if(e.fire<=0){shoot(e,'e');const f=ENEMY_TYPES[e.type].fireInterval;e.fire=rand(f[0],f[1])}}}
function updateBullets(dt){for(const b of bullets){b.x+=b.dx*b.speed*dt;b.y+=b.dy*b.speed*dt;if(bulletHitsObstacle(b))continue;if(!b.dead&&base.alive&&hit(b,base)){b.dead=1;damageBase();continue}if(b.owner==='p'){for(const e of enemies)if(!b.dead&&e.alive&&hit(b,e)){b.dead=1;e.hp-=b.power;explosion(b.x,b.y,e.color,7);if(e.hp<=0){e.alive=0;score+=e.score;kills++;explosion(e.x+e.w/2,e.y+e.h/2,e.color,20);sfx('boom');maybeDrop(e.x+e.w/2,e.y+e.h/2)}}}else if(!b.dead&&player.alive&&hit(b,player)){b.dead=1;damagePlayer()}if(b.x<OFFSET_X-20||b.y<OFFSET_Y-20||b.x>OFFSET_X+COLS*TILE_SIZE+20||b.y>OFFSET_Y+ROWS*TILE_SIZE+20)b.dead=1}}
function checkWave(dt){const level=CAMPAIGN_LEVELS[levelIndex];if(waveTransition>0){waveTransition-=dt;if(waveTransition<=0)beginWave(waveIndex+1);return}spawnTimer-=dt;if(spawnQueue.length&&spawnTimer<=0&&enemies.length<level.maxActive){if(spawnEnemy())spawnTimer=level.id>40?.38:level.id>20?.48:.62;else spawnTimer=.18}if(!spawnQueue.length&&!enemies.length){if(waveIndex<2){waveTransition=.85;toast(`Волна ${waveIndex+1} очищена`)}else levelClear()}}
function update(dt){if(!player?.alive||!base?.alive||paused)return;updatePlayer(dt);updateEnemies(dt);updateBullets(dt);for(const p of pickups){p.life-=dt;if(hit(player,p))applyPickup(p);if(p.life<=0)p.dead=1}for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96}obstacles=obstacles.filter(o=>o.type!=='BRICK'||o.segments!==0);enemies=enemies.filter(e=>e.alive);bullets=bullets.filter(b=>!b.dead);pickups=pickups.filter(p=>!p.dead);particles=particles.filter(p=>p.life>0);checkWave(dt);stats()}
function drawGround(){ctx.fillStyle='#0a0d12';ctx.fillRect(0,0,W,H);ctx.fillStyle='#0e1219';ctx.fillRect(OFFSET_X,OFFSET_Y,COLS*TILE_SIZE,ROWS*TILE_SIZE);ctx.strokeStyle='#ffffff09';ctx.lineWidth=1;for(let i=0;i<=COLS;i++){const x=OFFSET_X+i*TILE_SIZE;ctx.beginPath();ctx.moveTo(x,OFFSET_Y);ctx.lineTo(x,OFFSET_Y+ROWS*TILE_SIZE);ctx.stroke()}for(let i=0;i<=ROWS;i++){const y=OFFSET_Y+i*TILE_SIZE;ctx.beginPath();ctx.moveTo(OFFSET_X,y);ctx.lineTo(OFFSET_X+COLS*TILE_SIZE,y);ctx.stroke()}for(const k of iceCells){const [cc,rr]=k.split(',').map(Number);drawIce(cc,rr)}}
function drawIce(cc,rr){const x=px(cc),y=py(rr);ctx.fillStyle='#8edcf2';ctx.fillRect(x,y,TILE_SIZE,TILE_SIZE);ctx.fillStyle='#c9f4ff';ctx.fillRect(x+4,y+5,13,3);ctx.fillRect(x+25,y+25,10,3);ctx.strokeStyle='#e9fbff';ctx.beginPath();ctx.moveTo(x+18,y+10);ctx.lineTo(x+12,y+22);ctx.lineTo(x+21,y+29);ctx.stroke()}
function drawWater(o){const x=o.x,y=o.y,t=performance.now()/240;ctx.fillStyle='#235a9a';ctx.fillRect(x,y,o.w,o.h);ctx.fillStyle='#4b91d4';for(let r=7;r<o.h;r+=12){const off=((Math.floor(t)+r)%8);ctx.fillRect(x+3+off,y+r,13,3);ctx.fillRect(x+23-off/2,y+r+3,11,2)}}
function drawSteel(o){ctx.fillStyle='#737f90';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#9ca7b5';ctx.fillRect(o.x+4,o.y+4,o.w-8,4);ctx.strokeStyle='#bfc8d2';ctx.strokeRect(o.x+2,o.y+2,o.w-4,o.h-4);ctx.fillStyle='#3e4855';for(const [dx,dy] of [[6,7],[31,7],[6,31],[31,31]])ctx.fillRect(o.x+dx,o.y+dy,3,3)}
function drawBrickSegment(x,y,w,h,damaged=0){ctx.fillStyle=damaged?'#7b4334':'#9b523d';ctx.fillRect(x,y,w,h);ctx.fillStyle='#c27459';ctx.fillRect(x+2,y+2,w-4,3);ctx.fillRect(x+2,y+10,w-4,2);ctx.fillStyle='#5b3028';ctx.fillRect(x+w/2-1,y+2,2,8);ctx.fillRect(x+w/3,y+12,2,h-14);ctx.strokeStyle='#d18b6d';ctx.strokeRect(x+.5,y+.5,w-1,h-1)}
function drawBrick(o){for(const s of brickSegmentRects(o))drawBrickSegment(s.x,s.y,s.w,s.h,o.segments!==15)}
function drawBase(){const ratio=base.hp/base.maxHp,x=base.x,y=base.y;ctx.save();ctx.fillStyle='#0008';ctx.fillRect(x+4,y+5,base.w,base.h);ctx.fillStyle='#5d6670';ctx.fillRect(x-4,y-5,base.w+8,8);ctx.fillStyle=ratio>.66?'#d7b64d':ratio>.33?'#c68743':'#a95640';ctx.fillRect(x,y,base.w,base.h);ctx.strokeStyle='#f0dfa0';ctx.strokeRect(x+1,y+1,base.w-2,base.h-2);ctx.fillStyle='#222018';ctx.fillRect(x+12,y+11,14,23);ctx.fillStyle='#090b0e';ctx.fillRect(x+5,y+13,6,4);ctx.fillRect(x+27,y+13,6,4);ctx.strokeStyle='#bfcbd6';ctx.beginPath();ctx.moveTo(x+29,y);ctx.lineTo(x+29,y-14);ctx.stroke();ctx.fillStyle='#ed6a62';ctx.fillRect(x+29,y-14,9,5);ctx.fillStyle='#111';ctx.fillRect(x,y-10,base.w,4);ctx.fillStyle=ratio>.66?'#74e0a1':ratio>.33?'#f2ca4b':'#ed6a62';ctx.fillRect(x,y-10,base.w*ratio,4);ctx.restore()}
function tank(t,col){ctx.save();ctx.translate(t.x+t.w/2,t.y+t.h/2);ctx.rotate(t.dir==='up'?0:t.dir==='right'?Math.PI/2:t.dir==='down'?Math.PI:-Math.PI/2);ctx.fillStyle=col;ctx.fillRect(-16,-18,6,36);ctx.fillRect(10,-18,6,36);ctx.fillRect(-10,-13,20,26);ctx.fillStyle='#e7edf7';ctx.fillRect(-4,-9,8,15);ctx.fillRect(-2,-25,4,20);if(t.maxHp>1){ctx.fillStyle='#111';ctx.fillRect(-9,11,18,3);ctx.fillStyle=t.hp/t.maxHp>.5?'#74e0a1':'#f2ca4b';ctx.fillRect(-9,11,18*(t.hp/t.maxHp),3)}ctx.restore()}
function drawBush(cc,rr){const x=px(cc),y=py(rr);ctx.save();ctx.globalAlpha=.92;const colors=['#23582f','#2e7139','#3d8847'];for(let i=0;i<13;i++){ctx.fillStyle=colors[i%3];const dx=(i*13)%36,dy=(i*17)%34;ctx.fillRect(x+2+dx,y+2+dy,9,8)}ctx.restore()}
function draw(){drawGround();for(const o of obstacles)if(o.type==='WATER')drawWater(o);for(const o of obstacles)if(o.type==='STEEL')drawSteel(o);else if(o.type==='BRICK')drawBrick(o);drawBase();if(player?.alive){if(performance.now()<shieldUntil){ctx.strokeStyle='#79c8ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(player.x+16,player.y+18,27,0,Math.PI*2);ctx.stroke()}tank(player,'#74e0a1')}for(const e of enemies)tank(e,e.color);for(const b of bullets){ctx.fillStyle=b.owner==='p'?'#f2ca4b':'#ff8c7e';ctx.fillRect(b.x,b.y,b.w,b.h)}for(const p of pickups){ctx.fillStyle=p.kind==='rapid'?'#f2ca4b':p.kind==='shield'?'#6fb2ff':p.kind==='repair'?'#d9a76a':'#74e0a1';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#111';ctx.font='bold 14px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.kind==='rapid'?'⚡':p.kind==='shield'?'◆':p.kind==='repair'?'R':'+',p.x+12,p.y+12)}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.col;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const k of bushCells){const [cc,rr]=k.split(',').map(Number);drawBush(cc,rr)}}
function loop(t){if(!running)return;lastFrameWall=performance.now();try{const dt=Math.min(.033,Math.max(0,(t-last)/1000));last=t;update(dt);draw()}catch(err){console.error('game-frame-error',err);last=performance.now()}if(running)raf=requestAnimationFrame(loop)}
function kickLoop(){if(!running||paused)return;cancelAnimationFrame(raf);last=performance.now();lastFrameWall=last;raf=requestAnimationFrame(loop)}
function saveScore(){const a=JSON.parse(localStorage.getItem('retroScores')||'[]');a.push({score,level:CAMPAIGN_LEVELS[levelIndex].id,at:new Date().toLocaleString('ru-RU')});a.sort((a,b)=>b.score-a.score);localStorage.setItem('retroScores',JSON.stringify(a.slice(0,10)));renderScores()}
function renderScores(){const a=JSON.parse(localStorage.getItem('retroScores')||'[]');$('scores').innerHTML=a.length?a.map(v=>`<li><strong>${v.score}</strong> очков · уровень ${v.level||'-'} · ${v.at}</li>`).join(''):'<li>Пока пусто — начните кампанию.</li>'}
function showResult({badge,title,text,button,mode,mini=''}){running=false;paused=false;cancelAnimationFrame(raf);keys={};resetStick();primaryMode=mode;$('resultBadge').textContent=badge;$('resultTitle').textContent=title;$('resultText').textContent=text;$('primaryAction').textContent=button;$('resultMini').textContent=mini;$('over').classList.remove('hidden');fitGameBurst()}
function levelClear(){if(!running)return;const level=CAMPAIGN_LEVELS[levelIndex];score+=500+level.id*35+base.hp*150;sfx('win');stats();if(levelIndex<CAMPAIGN_LEVELS.length-1)showResult({badge:'УРОВЕНЬ ПРОЙДЕН',title:`${level.id}. ${level.name}`,text:`Счёт: ${score}. Все 3 волны уничтожены.`,button:'Следующий уровень',mode:'next',mini:`Впереди: ${CAMPAIGN_LEVELS[levelIndex+1].id}. ${CAMPAIGN_LEVELS[levelIndex+1].name}`});else{saveScore();showResult({badge:'КАМПАНИЯ ПРОЙДЕНА',title:'Последняя оборона выдержала!',text:`Все 50 уровней и 150 волн пройдены. Итог: ${score} очков.`,button:'Пройти заново',mode:'restart',mini:'Результат сохранён в локальной таблице рекордов.'})}}
function finish(win,reason){if(!running)return;sfx('lose');if(retriesRemaining>0){showResult({badge:'ПОРАЖЕНИЕ',title:'Оборона прорвана',text:`${reason}. Можно заново начать уровень ${CAMPAIGN_LEVELS[levelIndex].id}.`,button:'Повторить уровень',mode:'retry',mini:`Продолжений осталось: ${retriesRemaining}. Уровень начнётся с волны 1/3 и 3 жизнями.`});return}saveScore();showResult({badge:'ПОРАЖЕНИЕ',title:'Попытки закончились',text:`${reason}. Результат: ${score} очков.`,button:'Начать кампанию заново',mode:'restart',mini:`Дойдён уровень ${CAMPAIGN_LEVELS[levelIndex].id} из 50.`})}
function fitGame(){const game=$('game');if(!game||game.classList.contains('hidden'))return;const vv=window.visualViewport,vw=Math.floor(vv?vv.width:window.innerWidth),vh=Math.floor(vv?vv.height:window.innerHeight);game.style.left=(vv?vv.offsetLeft:0)+'px';game.style.top=(vv?vv.offsetTop:0)+'px';game.style.width=vw+'px';game.style.height=vh+'px';const hud=game.querySelector('.hud'),stage=game.querySelector('.stage'),cs=getComputedStyle(game),pyv=parseFloat(cs.paddingTop)+parseFloat(cs.paddingBottom),availableH=Math.max(120,vh-hud.getBoundingClientRect().height-pyv-7),availableW=Math.max(160,vw-16);stage.style.height=availableH+'px';stage.style.width='100%';const scale=Math.min(availableW/W,availableH/H),cw=Math.floor(W*scale),ch=Math.floor(H*scale);c.style.width=cw+'px';c.style.height=ch+'px';c.style.left='50%';c.style.top='50%';c.style.transform='translate(-50%,-50%)'}
function fitGameBurst(){clearTimeout(refitTimer);fitGame();requestAnimationFrame(fitGame);setTimeout(fitGame,80);setTimeout(fitGame,220);refitTimer=setTimeout(fitGame,430)}
function showGame(){document.documentElement.style.overflow='hidden';document.body.classList.add('playing');$('game').classList.remove('hidden');$('over').classList.add('hidden');$('pauseModal').classList.add('hidden');window.scrollTo(0,0);audio();resetCampaign();fitGameBurst()}
function showMenu(){running=false;paused=false;cancelAnimationFrame(raf);keys={};resetStick();document.body.classList.remove('playing');document.documentElement.style.overflow='';$('game').classList.add('hidden');$('over').classList.add('hidden');$('pauseModal').classList.add('hidden');renderScores()}
function pauseGame(){if(!running||paused)return;paused=true;keys={};resetStick();cancelAnimationFrame(raf);$('pauseModal').classList.remove('hidden');fitGameBurst()}
function resumeGame(){if(!paused)return;paused=false;$('pauseModal').classList.add('hidden');running=true;kickLoop();fitGameBurst()}
$('play').onclick=showGame;$('pause').onclick=pauseGame;$('resume').onclick=resumeGame;$('pauseMenu').onclick=showMenu;$('toMenu').onclick=showMenu;
$('primaryAction').onclick=()=>{if(primaryMode==='next'){levelIndex++;retriesRemaining=2;levelStartScore=score;startLevel()}else if(primaryMode==='retry'){retriesRemaining--;score=levelStartScore;lives=3;rapidUntil=0;shieldUntil=0;startLevel()}else resetCampaign()};
$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'🔊':'🔇';if(soundOn)sfx('power')};
$('share').onclick=async()=>{const d={title:'Игры нашего детства',text:'Танковая база — 50 уровней и 150 волн',url:location.href};try{if(navigator.share)await navigator.share(d);else await navigator.clipboard.writeText(location.href)}catch{}};
const km={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',' ':'fire'};
addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();paused?resumeGame():pauseGame();return}if(km[e.key]){e.preventDefault();keys[km[e.key]]=1}},{passive:false});addEventListener('keyup',e=>{if(km[e.key]){e.preventDefault();keys[km[e.key]]=0}},{passive:false});
for(const b of document.querySelectorAll('[data-k]')){const k=b.dataset.k,down=e=>{e.preventDefault();audio();keys[k]=1;b.dataset.pressed='1';try{b.setPointerCapture(e.pointerId)}catch{}},up=e=>{e.preventDefault();keys[k]=0;delete b.dataset.pressed;try{if(b.hasPointerCapture(e.pointerId))b.releasePointerCapture(e.pointerId)}catch{}};b.addEventListener('pointerdown',down,{passive:false});b.addEventListener('pointerup',up,{passive:false});b.addEventListener('pointercancel',up,{passive:false});b.addEventListener('lostpointercapture',up,{passive:false});b.addEventListener('contextmenu',e=>e.preventDefault())}
const pad=$('touchpad'),stick=$('stick');function resetStick(){touch.active=false;touch.id=null;touch.x=touch.y=0;if(stick)stick.style.transform='translate(0px,0px)';keys.up=keys.down=keys.left=keys.right=0}
function updateStick(clientX,clientY){if(!pad||!stick)return;const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=clientX-cx,dy=clientY-cy,len=Math.hypot(dx,dy);if(len>touch.max){dx=dx/len*touch.max;dy=dy/len*touch.max}stick.style.transform=`translate(${dx}px,${dy}px)`;touch.x=dx/touch.max;touch.y=dy/touch.max;keys.up=keys.down=keys.left=keys.right=0;if(Math.abs(touch.x)<.18&&Math.abs(touch.y)<.18)return;if(Math.abs(touch.x)>Math.abs(touch.y))keys[touch.x>0?'right':'left']=1;else keys[touch.y>0?'down':'up']=1}
if(pad){pad.addEventListener('pointerdown',e=>{e.preventDefault();audio();touch.active=true;touch.id=e.pointerId;try{pad.setPointerCapture(e.pointerId)}catch{}updateStick(e.clientX,e.clientY)},{passive:false});pad.addEventListener('pointermove',e=>{if(touch.active&&e.pointerId===touch.id){e.preventDefault();updateStick(e.clientX,e.clientY)}},{passive:false});for(const ev of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(ev,e=>{if(e.pointerId===touch.id){e.preventDefault();resetStick()}},{passive:false})}
addEventListener('blur',()=>{keys={};resetStick();fitGameBurst()});document.addEventListener('visibilitychange',()=>{keys={};resetStick();if(document.visibilityState==='visible'&&running&&!paused)kickLoop();if(document.visibilityState==='visible')fitGameBurst()});addEventListener('pageshow',()=>{if(running&&!paused)kickLoop();fitGameBurst()});addEventListener('focus',()=>{if(running&&!paused)kickLoop();fitGameBurst()});setInterval(()=>{if(running&&!paused&&document.visibilityState==='visible'&&performance.now()-lastFrameWall>1200)kickLoop();if(document.body.classList.contains('playing'))fitGame()},800);addEventListener('resize',fitGameBurst);addEventListener('orientationchange',()=>setTimeout(fitGameBurst,140));if(window.visualViewport){visualViewport.addEventListener('resize',fitGameBurst);visualViewport.addEventListener('scroll',fitGameBurst)}
renderScores();